ALTER TABLE "match_frames"
  ADD COLUMN IF NOT EXISTS "breakAndRun" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "player_comp_stats"
  ADD COLUMN IF NOT EXISTS "singlesWon" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "doublesWon" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "brWon" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "mvpScore" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS "player_comp_stats_mvpScore_idx"
  ON "player_comp_stats"("mvpScore");
